name: Automated Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.ai/install.sh | sh
          ollama serve &
          sleep 5
          # Use a powerful model for code review
          ollama pull llama3.1:latest

      - name: Install rev.py and dependencies
        run: |
          pip install -r requirements.txt

      - name: Get changed files
        id: changed-files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD)
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run automated code review
        id: review
        run: |
          # Create review using rev.py
          python rev.py "Review the following changes and provide detailed feedback on code quality, security, performance, and best practices" > review.md

          # Extract issues and suggestions
          cat review.md

      - name: Run static analysis
        continue-on-error: true
        run: |
          # Python analysis
          flake8 . --exit-zero --format=json > flake8-report.json
          pylint **/*.py --output-format=json > pylint-report.json || true

          # For JavaScript/TypeScript
          # npm run lint -- --format=json > eslint-report.json || true

      - name: Check code complexity
        continue-on-error: true
        run: |
          pip install radon
          radon cc . -j > complexity-report.json
          radon mi . -j > maintainability-report.json

      - name: Post review comments
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            // Read review from rev.py
            const review = fs.readFileSync('review.md', 'utf8');

            // Parse static analysis reports
            let lintIssues = [];
            try {
              const flake8 = JSON.parse(fs.readFileSync('flake8-report.json'));
              lintIssues = flake8.map(issue => ({
                path: issue.filename,
                line: issue.line_number,
                message: issue.text,
                severity: issue.severity
              }));
            } catch (e) {
              console.log('No flake8 report');
            }

            // Post main review comment
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'COMMENT',
              body: `## 🤖 Automated Code Review\n\n${review}\n\n---\n*Generated by rev.py*`
            });

            // Post inline comments for lint issues
            for (const issue of lintIssues.slice(0, 10)) {  // Limit to 10 comments
              try {
                await github.rest.pulls.createReviewComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  body: `**${issue.severity}:** ${issue.message}`,
                  path: issue.path,
                  line: issue.line,
                  side: 'RIGHT'
                });
              } catch (e) {
                console.log(`Could not comment on ${issue.path}:${issue.line}`);
              }
            }

      - name: Check for code smells
        run: |
          python rev.py "Analyze the code for common code smells and anti-patterns" > code-smells.md

      - name: Security review
        run: |
          python rev.py "Perform a security review focusing on common vulnerabilities" > security-review.md

      - name: Performance analysis
        run: |
          python rev.py "Analyze the code for potential performance issues" > performance-review.md

      - name: Post detailed analysis
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            const codeSmells = fs.readFileSync('code-smells.md', 'utf8');
            const security = fs.readFileSync('security-review.md', 'utf8');
            const performance = fs.readFileSync('performance-review.md', 'utf8');

            const detailedReview = `## 📋 Detailed Analysis

            ### Code Quality
            ${codeSmells}

            ### Security
            ${security}

            ### Performance
            ${performance}

            ---
            *Automated analysis by rev.py*
            `;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: detailedReview
            });

      - name: Upload review reports
        uses: actions/upload-artifact@v3
        with:
          name: review-reports
          path: |
            review.md
            code-smells.md
            security-review.md
            performance-review.md
            *-report.json

      - name: Check if changes needed
        id: check-approval
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('review.md', 'utf8');

            // Simple heuristic: check for critical issues
            const hasCriticalIssues = review.toLowerCase().includes('critical') ||
                                     review.toLowerCase().includes('security issue') ||
                                     review.toLowerCase().includes('must fix');

            if (hasCriticalIssues) {
              core.setOutput('needs_changes', 'true');
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                event: 'REQUEST_CHANGES',
                body: '⚠️ Critical issues found. Please address before merging.'
              });
            } else {
              core.setOutput('needs_changes', 'false');
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                event: 'APPROVE',
                body: '✅ Code review complete. No critical issues found!'
              });
            }
