name: Auto-Update Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'app/**'
      - '**/*.py'
      - '**/*.js'
      - '**/*.ts'
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.ai/install.sh | sh
          ollama serve &
          sleep 5
          ollama pull llama3.1:latest

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate API documentation
        run: |
          python rev.py "Generate comprehensive API documentation from code in docs/API.md"

      - name: Update README examples
        run: |
          python rev.py "Update README.md with current usage examples from codebase"

      - name: Generate architecture documentation
        run: |
          python rev.py "Analyze codebase structure and update docs/ARCHITECTURE.md"

      - name: Add docstrings to undocumented code
        run: |
          python rev.py "Add docstrings to all functions missing documentation"

      - name: Generate CHANGELOG
        run: |
          python rev.py "Update CHANGELOG.md with changes since last release"

      - name: Create tutorial if needed
        run: |
          if [ ! -f "docs/TUTORIAL.md" ]; then
            python rev.py "Create beginner tutorial in docs/TUTORIAL.md"
          fi

      - name: Validate documentation
        run: |
          # Check for broken links
          pip install linkchecker || true
          linkchecker docs/ || true

          # Check code examples in docs
          python -c "
          import re
          import subprocess
          from pathlib import Path

          for doc in Path('docs').glob('*.md'):
              content = doc.read_text()
              # Extract Python code blocks
              code_blocks = re.findall(r'\`\`\`python\n(.*?)\`\`\`', content, re.DOTALL)
              for i, code in enumerate(code_blocks):
                  try:
                      compile(code, f'{doc.name}_block_{i}', 'exec')
                  except SyntaxError as e:
                      print(f'Syntax error in {doc.name} block {i}: {e}')
          "

      - name: Build documentation site
        run: |
          # For MkDocs
          pip install mkdocs mkdocs-material
          mkdocs build || true

          # For Sphinx
          # pip install sphinx sphinx-rtd-theme
          # cd docs && make html

      - name: Commit documentation updates
        run: |
          git config user.name "rev-docs-bot"
          git config user.email "docs@rev.ai"

          git add docs/ README.md CHANGELOG.md **/*.py **/*.js **/*.ts
          git commit -m "docs: Auto-update documentation [skip ci]" || exit 0

          git push

      - name: Create PR for major doc changes
        if: github.event_name == 'workflow_dispatch'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="docs-update-$(date +%Y%m%d)"
          git checkout -b $BRANCH

          git add .
          git commit -m "docs: Comprehensive documentation update" || exit 0

          git push -u origin $BRANCH

          gh pr create \
            --title "📚 Documentation Update" \
            --label "documentation" \
            --body "$(cat <<EOF
          ## Documentation Updates

          Automated documentation updates including:
          - ✅ API documentation
          - ✅ Code docstrings
          - ✅ Architecture docs
          - ✅ Changelog
          - ✅ Usage examples

          ### Changes
          - Updated API documentation to reflect current codebase
          - Added missing docstrings
          - Refreshed examples and tutorials
          - Updated architecture documentation

          ### Validation
          - Code examples verified for syntax
          - Links checked
          - Documentation site builds successfully

          ---
          *Auto-generated by rev.py*
          EOF
          )"

      - name: Deploy documentation
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Deploy to GitHub Pages
          mkdocs gh-deploy --force || true

          # Or deploy to other hosting
          # npm run deploy-docs
          # rsync -avz site/ user@server:/var/www/docs/

      - name: Notify on Slack/Discord
        if: success()
        run: |
          # Example Slack notification
          curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
            -H 'Content-Type: application/json' \
            -d '{
              "text": "📚 Documentation updated automatically",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Documentation Updated*\nAPI docs, examples, and guides have been refreshed."
                  }
                }
              ]
            }' || true

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: |
            docs/
            site/
            README.md
            CHANGELOG.md
