name: Security Scan and Auto-Fix

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install security scanners
        run: |
          pip install bandit safety pip-audit
          # For Node.js projects
          # npm install -g npm-audit snyk

      - name: Run Bandit security scan
        id: bandit
        continue-on-error: true
        run: |
          bandit -r . -f json -o bandit-report.json || true
          bandit -r . || true

      - name: Check for vulnerable dependencies
        id: safety
        continue-on-error: true
        run: |
          safety check --json > safety-report.json || true
          safety check || true

      - name: Run pip-audit
        id: pip-audit
        continue-on-error: true
        run: |
          pip-audit --desc > pip-audit-report.txt || true

      - name: Install Ollama for auto-fix
        if: |
          steps.bandit.outcome == 'failure' ||
          steps.safety.outcome == 'failure' ||
          steps.pip-audit.outcome == 'failure'
        run: |
          curl -fsSL https://ollama.ai/install.sh | sh
          ollama serve &
          sleep 5
          ollama pull llama3.1:latest

      - name: Install rev.py
        if: |
          steps.bandit.outcome == 'failure' ||
          steps.safety.outcome == 'failure' ||
          steps.pip-audit.outcome == 'failure'
        run: |
          pip install -r requirements.txt

      - name: Auto-fix security issues
        if: steps.bandit.outcome == 'failure'
        run: |
          echo "Security issues found. Attempting auto-fix..."
          python rev.py "Fix security vulnerabilities found by Bandit scanner"

      - name: Update vulnerable dependencies
        if: steps.safety.outcome == 'failure' || steps.pip-audit.outcome == 'failure'
        run: |
          python rev.py "Update vulnerable dependencies to secure versions"

      - name: Re-run security scans
        run: |
          echo "Verifying fixes..."
          bandit -r . || echo "Some issues remain"
          safety check || echo "Some vulnerabilities remain"

      - name: Create security issue if critical vulnerabilities found
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let banditIssues = '';
            let safetyIssues = '';

            try {
              const bandit = JSON.parse(fs.readFileSync('bandit-report.json'));
              banditIssues = bandit.results
                .filter(r => r.issue_severity === 'HIGH' || r.issue_severity === 'CRITICAL')
                .map(r => `- **${r.issue_text}** in \`${r.filename}:${r.line_number}\``)
                .join('\n');
            } catch (e) {}

            try {
              const safety = JSON.parse(fs.readFileSync('safety-report.json'));
              safetyIssues = safety.map(v =>
                `- **${v.package}** ${v.installed_version} (${v.vulnerability})`
              ).join('\n');
            } catch (e) {}

            if (banditIssues || safetyIssues) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'ðŸš¨ Security Vulnerabilities Detected',
                labels: ['security', 'high-priority'],
                body: `## Security Scan Results

            ${banditIssues ? `### Code Security Issues\n${banditIssues}\n` : ''}
            ${safetyIssues ? `### Vulnerable Dependencies\n${safetyIssues}\n` : ''}

            ### Action Required
            Please review and address these security issues immediately.

            **Scan Date:** ${new Date().toISOString()}
            **Workflow Run:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            ---
            *Auto-generated by Security Scanner*
            `
              });
            }

      - name: Create PR with fixes
        if: |
          steps.bandit.outcome == 'failure' ||
          steps.safety.outcome == 'failure'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "rev-bot"
          git config user.email "bot@rev.ai"

          BRANCH="security-fixes-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH

          git add .
          git commit -m "Security: Auto-fix vulnerabilities" || exit 0

          git push -u origin $BRANCH

          gh pr create \
            --title "ðŸ”’ Security: Auto-fix vulnerabilities" \
            --label "security" \
            --body "$(cat <<EOF
          ## Security Fixes

          This PR contains automated fixes for security vulnerabilities detected by:
          - Bandit (code security scanner)
          - Safety (dependency vulnerability scanner)
          - pip-audit (dependency auditor)

          ### Changes Made
          - Fixed security issues in code
          - Updated vulnerable dependencies
          - Applied security best practices

          ### Testing
          - Re-ran security scans
          - Verified functionality

          **âš ï¸ IMPORTANT:** Please review these changes carefully before merging.

          ---
          *Auto-generated by rev.py security scanner*
          EOF
          )"

      - name: Upload security reports
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json
            pip-audit-report.txt
