name: Improve Test Coverage

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:
    inputs:
      target_coverage:
        description: 'Target coverage percentage'
        required: false
        default: '80'

jobs:
  improve-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.ai/install.sh | sh
          ollama serve &
          sleep 5
          ollama pull llama3.1:latest

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install pytest pytest-cov

      - name: Run coverage analysis
        id: coverage
        run: |
          pytest --cov=. --cov-report=json --cov-report=term
          COVERAGE=$(python -c "import json; print(json.load(open('coverage.json'))['totals']['percent_covered'])")
          echo "current_coverage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "Current coverage: $COVERAGE%"

      - name: Add tests to improve coverage
        if: steps.coverage.outputs.current_coverage < inputs.target_coverage || '80'
        run: |
          TARGET=${{ inputs.target_coverage || '80' }}
          CURRENT=${{ steps.coverage.outputs.current_coverage }}

          python rev.py "Analyze test coverage report and add tests to reach ${TARGET}% coverage (currently at ${CURRENT}%)"

      - name: Run tests again
        run: |
          pytest --cov=. --cov-report=json --cov-report=term --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/

      - name: Create PR with new tests
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "rev-bot"
          git config user.email "bot@rev.ai"

          BRANCH="improve-coverage-$(date +%Y%m%d)"
          git checkout -b $BRANCH

          git add .
          git commit -m "Improve test coverage to ${{ inputs.target_coverage || '80' }}%" || exit 0

          git push -u origin $BRANCH

          NEW_COVERAGE=$(python -c "import json; print(json.load(open('coverage.json'))['totals']['percent_covered'])")

          gh pr create \
            --title "Improve test coverage: ${{ steps.coverage.outputs.current_coverage }}% → ${NEW_COVERAGE}%" \
            --body "$(cat <<EOF
          ## Test Coverage Improvement

          **Before:** ${{ steps.coverage.outputs.current_coverage }}%
          **After:** ${NEW_COVERAGE}%
          **Target:** ${{ inputs.target_coverage || '80' }}%

          ### Changes
          - Added tests for previously uncovered code
          - Improved edge case testing
          - Added integration tests where needed

          ### Coverage Report
          See attached coverage report artifact for details.

          ---
          *Auto-generated by rev.py*
          EOF
          )"

      - name: Post coverage comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const coverage = JSON.parse(fs.readFileSync('coverage.json'));
            const percent = coverage.totals.percent_covered.toFixed(2);

            const comment = `## 📊 Coverage Report

            **Total Coverage:** ${percent}%
            **Target:** ${{ inputs.target_coverage || '80' }}%

            ${percent >= ${{ inputs.target_coverage || '80' }} ? '✅ Coverage target met!' : '⚠️ Coverage below target'}

            [View detailed coverage report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;

            // Post as issue comment if triggered manually
            if (context.eventName === 'workflow_dispatch') {
              // Create an issue for tracking
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Coverage Report - ${new Date().toISOString().split('T')[0]}`,
                body: comment
              });
            }
